name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run unittests
        run: python -m unittest discover -s tests -t tests -v
